Make sure the service name is the same everywhere
nicka/coinboss pull request #6
Opened 2017-07-13 13:41 UTC by svdgraaf

The naming convention differs. Sometimes with capital, sometimes without. It's better to have them consistent, as this makes things more predictable.

Merging this PR will make everything use the central service designator, which will always be consistent.

2017-07-13 19:06 UTC, nicka requested changes
Also be sure to run `yarn test`

2017-07-13 19:06 UTC, nicka commented on lib/cloudWatch.js
> +    this.namespace = process.env.SERVICE_NAME;
```js
this.namespace = process.env.SERVICE_NAME || 'coinboss'; 
```

2017-07-14 14:32 UTC, svdgraaf commented on lib/cloudWatch.js
> +    this.namespace = process.env.SERVICE_NAME;
Done

2017-07-14 14:32 UTC, svdgraaf commented
@nicka updated :)

2017-07-14 15:23 UTC, nicka approved these changes

2017-07-14 15:23 UTC, merged

2017-07-16 14:44 UTC, tvb commented
@svdgraaf @nicka This change actually limits the way to push different metrics (like from different exchanges) to different namespaces. It is set to to `service: ${file(package.json):name}` which is 
```
{
  "name": "coinboss",
...
```