Feature/kraken
nicka/coinboss pull request #9
Opened 2017-07-17 17:36 UTC by tvb

Adding the Kraken Exchange

2017-07-17 19:57 UTC, nicka commented
Sorry, please rebase... Added CI

2017-07-17 20:03 UTC, tvb commented
@nicka done.

2017-07-17 20:13 UTC, nicka commented
`eslint --fix` 😉

2017-07-17 20:23 UTC, tvb commented
@nicka 

Not quite:
```
$ eslint . --fix
Cannot find module 'eslint-config-airbnb-base'
Referenced from: /Users/tristan/Google Drive/Prive/Code/coinboss/.eslintrc
Error: Cannot find module 'eslint-config-airbnb-base'
Referenced from: /Users/tristan/Google Drive/Prive/Code/coinboss/.eslintrc
    at ModuleResolver.resolve (/usr/local/lib/node_modules/eslint/lib/util/module-resolver.js:74:19)
    at resolve (/usr/local/lib/node_modules/eslint/lib/config/config-file.js:515:25)
    at load (/usr/local/lib/node_modules/eslint/lib/config/config-file.js:584:26)
    at configExtends.reduceRight (/usr/local/lib/node_modules/eslint/lib/config/config-file.js:421:36)
    at Array.reduceRight (native)
    at applyExtends (/usr/local/lib/node_modules/eslint/lib/config/config-file.js:405:28)
    at loadFromDisk (/usr/local/lib/node_modules/eslint/lib/config/config-file.js:556:22)
    at Object.load (/usr/local/lib/node_modules/eslint/lib/config/config-file.js:592:20)
    at Config.getLocalConfigHierarchy (/usr/local/lib/node_modules/eslint/lib/config.js:228:44)
    at Config.getConfigHierarchy (/usr/local/lib/node_modules/eslint/lib/config.js:182:43)
```

2017-07-17 20:24 UTC, nicka requested changes

2017-07-17 20:24 UTC, nicka commented on lib/kraken.js
> +  getBalance() {
Could you please remove this.

2017-07-17 20:24 UTC, nicka commented on handler.js
> +    kraken.getExchangeRates('Ask'),
Would it be possible to make Kraken optional? Maybe through an ENVIRONMENT variable?

Maybe something like this?

```js
export const getExchangeRates = (event, context, callback) => {
  const promisesQueue = [
    coinbase.getExchangeRates('Buy'),
    coinbase.getExchangeRates('Sell'),
  ];

  if (process.env.KRAKEN_ENABLED === 'enabled') { // Default to disabled
    promisesQueue.push(kraken.getExchangeRates('Buy'));
    promisesQueue.push(kraken.getExchangeRates('Ask'));
  }

  return Promise.all(promisesQueue)
    .then(() =>
      callback(null, { statusCode: 200, body: { message: 'Collected exchange rates.' } }),
    ...
```

2017-07-17 20:24 UTC, nicka commented on lib/coinbase.js
> +              namespace: `Coinbase`,
Please leave as is... All metrics should be within the main `coinbase` namespace. If you want to make them more specific please update `cloudWatch.js` to include something like:

```js
static setupBuySellDimensions(currency, localCurrency, provider = 'coinbase') {
    return [
      {
        Name: 'Provider',
        Value: provider,
      },
      {
        Name: 'CryptoCurrency',
        Value: currency,
      },
      {
        Name: 'LocalCurrency',
        Value: localCurrency,
      },
      {
        Name: 'Stage',
        Value: process.env.STAGE || 'dev',
      },
    ];
  }
```

2017-07-17 20:25 UTC, nicka commented
Did you run `yarn` before running `eslint`?

2017-07-17 20:26 UTC, tvb commented
I did now, same outcome.

2017-07-17 20:29 UTC, j4zz commented
Likely `yarn eslint . --fix` if you haven’t installed `eslint` globally.

2017-07-17 20:31 UTC, tvb commented
I ran `npm i -g eslint` but `yarn eslint . --fix` seems to work without errors.

2017-07-17 20:36 UTC, j4zz commented
@nicka Check out [eslint-staged](https://github.com/okonet/lint-staged) with husky if you don’t know it yet. Likely makes it easier for contributors to follow project-style since you could, for example, let the project automatically run formatting steps on a `precommit`.

2017-07-17 20:38 UTC, tvb commented on handler.js
> +    kraken.getExchangeRates('Ask'),
Sure, seems logical.

2017-07-17 20:41 UTC, tvb commented on lib/coinbase.js
> +              namespace: `Coinbase`,
Adding provider seems ok.  But what is the main namespace being called now? `Coinbase`, `coinbase` or `coinboss`.  I see three different namespaces now.

2017-07-17 20:42 UTC, tvb commented on lib/kraken.js
> +  getBalance() {
Sure but why?

2017-07-17 20:43 UTC, nicka commented on lib/coinbase.js
> +              namespace: `Coinbase`,
If you look at the CloudFormation alarms the namespace is always `Namespace: ${self:service}` which is coming from `service: ${file(package.json):name}`. Resulting in `coinboss`.

2017-07-17 20:45 UTC, tvb commented on lib/coinbase.js
> +              namespace: `Coinbase`,
Exactly, and you are mentioning `coinbase` as main namespace. So I got confused.

2017-07-17 20:46 UTC, nicka requested changes

2017-07-17 20:46 UTC, nicka commented on lib/kraken.js
> +  getBalance() {
Think it should be inside https://github.com/nicka/coinboss/pull/3 if we're going to merge it. For now, I think the balance does not add that much value.

2017-07-17 20:47 UTC, tvb commented on lib/kraken.js
> +  getBalance() {
Ok I will remove it.

2017-07-17 21:14 UTC, tvb commented
got 2 ✅  🎉 !

2017-07-17 21:40 UTC, nicka commented
Hehe for now! I'm adding some more Jest config tomorrow since the coverage did not check for the new kraken.js

2017-07-17 21:41 UTC, nicka commented
Also please update the .env.example and README.md for Kraken support.

2017-07-18 04:50 UTC, tvb commented
@nicka done

2017-08-01 05:59 UTC, nicka commented
Build is failing

2017-10-22 09:09 UTC, j4zz commented
@tvb What’s the status on this? I do think Kraken support would be valuable.

2017-10-22 18:03 UTC, tvb commented
@j4zz I moved on, but feel free to fix this PR and have @nicka include it 👍

2020-04-29 21:18 UTC, closed without merging